 # Check https://goreleaser.com/customization/env/
env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

# Check https://goreleaser.com/customization/hooks/
before:
  hooks:
  - go mod download
  - go mod tidy

# Check https://goreleaser.com/customization/build/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows

# Check https://goreleaser.com/customization/archive/
archives:
  - 
    name_template: "birdiecare_dbc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"  
    replacements:
      darwin: Darwin
      linux: Linux
      windows: windows
      386: i386
      amd64: x86_64
    files:
      - README.md

project_name: dbc

# Check https://goreleaser.com/customization/homebrew/
brews:
  - 
    homepage: 'https://github.com/birdicare/homebrew-dbc'
    description: 'Database Connect'
    folder: Formula
    commit_author:
      name: harrywm
      email: harry.morgan@birdie.care
    tap:
      owner: birdiecare
      name: dbc
    install: |
      bin.install "dbc"