name: Release

permissions: write-all

on:
  push:
    tags:
        - 'v[0-9]+.[0-9]+.[0-9]+' # Only build tag with semantic versioning format
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Install specific version of go
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.15
      # Run goreleaser with command line flag
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: -f .goreleaser.yaml release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}