name: "Release"

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: -f .goreleaser.yaml release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}