name: 'Tag'

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - '.go.mod'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
      - '.github/workflows/'
      
env:
  # AWS
  AWS_DEFAULT_REGION: eu-west-2
  AWS_REGION: eu-west-2

jobs: 
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.BIRDIECARE_TF_REGISTRY_READONLY }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: release
        with:
          semantic_version: 18
          branch: main
          working_directory: ./
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/changelog
            @google/semantic-release-replace-plugin
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump version and push tag
        if: steps.release.outcome == 'success'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1